# Generated by Django 3.2.6 on 2021-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211002_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
