# Generated by Django 3.2.6 on 2021-10-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
