# Generated by Django 3.2.6 on 2021-09-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='people_who_liked',
            field=models.JSONField(default=''),
        ),
    ]
